//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Drug
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Stock_Amount { get; set; }
        public Nullable<System.DateTime> Prod { get; set; }
        public Nullable<System.DateTime> Exp { get; set; }
    }
}
