//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public byte[] Photo { get; set; }
        public string Password { get; set; }
    }
}
